### ISSUE TITLE
RefreshToken Error

### ISSUE THREAD

**Issue by benjamin0809** [bartosz-io/jwt-auth-angular#8]
Hello, how can I catch the RefreshToken API error and then redirect to the login page.

**Comment by philip-firstorder** [comment]
1. First import the router and declare it in the constructor
https://github.com/bartosz-io/jwt-auth-angular/blob/6f7692225de4dcb5369d52bd5c1fc955dc57ab4b/src/app/auth/token.interceptor.ts#L13

> Change above line to this

```ts
import { Router } from '@angular/router';

constructor(public authService: AuthService, private router: Router) {
```

2. Then avoid refreshToken() POST response to be routed to handle401Error() function by the interceptor

https://github.com/bartosz-io/jwt-auth-angular/blob/6f7692225de4dcb5369d52bd5c1fc955dc57ab4b/src/app/auth/token.interceptor.ts#L22

> Change above line to this

```ts
        if (error instanceof HttpErrorResponse && error.status === 401 &&
            !httpRequest.url.endsWith('/refresh')) { // Don't handle the 401 error returned from refreshToken request
```

3. Third you must catch the refreshToken() error and redirect to login page, in my case I even provide the returnUrl in queryParams, so that after login I reroute the user back to the page he requested

```ts
return this.authService.refreshToken().pipe(
  switchMap((token: any) => {
    this.isRefreshing = false;
    this.refreshTokenSubject.next(token.jwt);
    return next.handle(this.addToken(request, token.jwt));
  }),
  catchError((error: any) => {
    this.router.navigate('/login' { queryParams: { returnUrl: this.router.url }});

    return of(error);
  })
);
```
